/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "discovery_service.h"

gboolean
discovery_service_if_get_all_instances (DiscoveryServiceIf *iface, GPtrArray ** _return, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, CuratorException ** ex1, GError **error)
{
  return DISCOVERY_SERVICE_IF_GET_INTERFACE (iface)->get_all_instances (iface, _return, projection, providerProjection, ex1, error);
}

gboolean
discovery_service_if_get_instance (DiscoveryServiceIf *iface, DiscoveryInstance ** _return, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, CuratorException ** ex1, GError **error)
{
  return DISCOVERY_SERVICE_IF_GET_INTERFACE (iface)->get_instance (iface, _return, projection, providerProjection, ex1, error);
}

gboolean
discovery_service_if_make_discovery_instance (DiscoveryServiceIf *iface, DiscoveryInstance ** _return, const gchar * name, const GByteArray * payload, const gint32 port, CuratorException ** ex1, GError **error)
{
  return DISCOVERY_SERVICE_IF_GET_INTERFACE (iface)->make_discovery_instance (iface, _return, name, payload, port, ex1, error);
}

gboolean
discovery_service_if_note_error (DiscoveryServiceIf *iface, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, const gchar * instanceId, CuratorException ** ex1, GError **error)
{
  return DISCOVERY_SERVICE_IF_GET_INTERFACE (iface)->note_error (iface, projection, providerProjection, instanceId, ex1, error);
}

gboolean
discovery_service_if_start_discovery (DiscoveryServiceIf *iface, DiscoveryProjection ** _return, const CuratorProjection * projection, const gchar * basePath, const DiscoveryInstance * yourInstance, CuratorException ** ex1, GError **error)
{
  return DISCOVERY_SERVICE_IF_GET_INTERFACE (iface)->start_discovery (iface, _return, projection, basePath, yourInstance, ex1, error);
}

gboolean
discovery_service_if_start_provider (DiscoveryServiceIf *iface, DiscoveryProviderProjection ** _return, const CuratorProjection * projection, const DiscoveryProjection * discoveryProjection, const gchar * serviceName, const ProviderStrategyType providerStrategy, const gint32 downTimeoutMs, const gint32 downErrorThreshold, CuratorException ** ex1, GError **error)
{
  return DISCOVERY_SERVICE_IF_GET_INTERFACE (iface)->start_provider (iface, _return, projection, discoveryProjection, serviceName, providerStrategy, downTimeoutMs, downErrorThreshold, ex1, error);
}

GType
discovery_service_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (DiscoveryServiceIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "DiscoveryServiceIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
discovery_service_if_interface_init (DiscoveryServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (DiscoveryServiceClient, discovery_service_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (TYPE_DISCOVERY_SERVICE_IF,
                                                discovery_service_if_interface_init))

enum _DiscoveryServiceClientProperties
{
  PROP_0,
  PROP_DISCOVERY_SERVICE_CLIENT_INPUT_PROTOCOL,
  PROP_DISCOVERY_SERVICE_CLIENT_OUTPUT_PROTOCOL
};

void
discovery_service_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  DiscoveryServiceClient *client = DISCOVERY_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_DISCOVERY_SERVICE_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_DISCOVERY_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
discovery_service_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  DiscoveryServiceClient *client = DISCOVERY_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_DISCOVERY_SERVICE_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_DISCOVERY_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean discovery_service_client_send_get_all_instances (DiscoveryServiceIf * iface, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "getAllInstances", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "getAllInstances_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "projection", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (projection), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "providerProjection", T_STRUCT, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (providerProjection), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean discovery_service_client_recv_get_all_instances (DiscoveryServiceIf * iface, GPtrArray ** _return, CuratorException ** ex1, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "getAllInstances", 15) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected getAllInstances", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_LIST)
          {
            {
              guint32 size;
              guint32 i;
              ThriftType element_type;

              if ((ret = thrift_protocol_read_list_begin (protocol, &element_type,&size, error)) < 0)
                return 0;
              xfer += ret;

              /* iterate through list elements */
              for (i = 0; i < size; i++)
              {
                DiscoveryInstance * _elem29 = NULL;
                if ( _elem29 != NULL)
                {
                  g_object_unref (_elem29);
                }
                _elem29 = g_object_new (TYPE_DISCOVERY_INSTANCE, NULL);
                if ((ret = thrift_struct_read (THRIFT_STRUCT (_elem29), protocol, error)) < 0)
                {
                  g_object_unref (_elem29);
                  return 0;
                }
                xfer += ret;
                g_ptr_array_add (*_return, _elem29);
              }
              if ((ret = thrift_protocol_read_list_end (protocol, error)) < 0)
                return 0;
              xfer += ret;
            }
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ex1 != NULL)
            {
              g_object_unref (*ex1);
            }
            *ex1 = g_object_new (TYPE_CURATOR_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ex1), protocol, error)) < 0)
            {
              g_object_unref (*ex1);
              *ex1 = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ex1 != NULL)
  {
      g_set_error (error, CURATOR_EXCEPTION_ERROR, CURATOR_EXCEPTION_ERROR_CODE, "CuratorException");
      return FALSE;
  }
  return TRUE;
}

gboolean discovery_service_client_get_all_instances (DiscoveryServiceIf * iface, GPtrArray ** _return, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, CuratorException ** ex1, GError ** error)
{
  if (!discovery_service_client_send_get_all_instances (iface, projection, providerProjection, error))
    return FALSE;
  if (!discovery_service_client_recv_get_all_instances (iface, _return, ex1, error))
    return FALSE;
  return TRUE;
}

gboolean discovery_service_client_send_get_instance (DiscoveryServiceIf * iface, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "getInstance", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "getInstance_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "projection", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (projection), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "providerProjection", T_STRUCT, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (providerProjection), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean discovery_service_client_recv_get_instance (DiscoveryServiceIf * iface, DiscoveryInstance ** _return, CuratorException ** ex1, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "getInstance", 11) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected getInstance", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ex1 != NULL)
            {
              g_object_unref (*ex1);
            }
            *ex1 = g_object_new (TYPE_CURATOR_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ex1), protocol, error)) < 0)
            {
              g_object_unref (*ex1);
              *ex1 = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ex1 != NULL)
  {
      g_set_error (error, CURATOR_EXCEPTION_ERROR, CURATOR_EXCEPTION_ERROR_CODE, "CuratorException");
      return FALSE;
  }
  return TRUE;
}

gboolean discovery_service_client_get_instance (DiscoveryServiceIf * iface, DiscoveryInstance ** _return, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, CuratorException ** ex1, GError ** error)
{
  if (!discovery_service_client_send_get_instance (iface, projection, providerProjection, error))
    return FALSE;
  if (!discovery_service_client_recv_get_instance (iface, _return, ex1, error))
    return FALSE;
  return TRUE;
}

gboolean discovery_service_client_send_make_discovery_instance (DiscoveryServiceIf * iface, const gchar * name, const GByteArray * payload, const gint32 port, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "makeDiscoveryInstance", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "makeDiscoveryInstance_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "name", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, name, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "payload", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_binary (protocol, ((GByteArray *) payload)->data, ((GByteArray *) payload)->len, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "port", T_I32, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, port, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean discovery_service_client_recv_make_discovery_instance (DiscoveryServiceIf * iface, DiscoveryInstance ** _return, CuratorException ** ex1, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "makeDiscoveryInstance", 21) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected makeDiscoveryInstance", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ex1 != NULL)
            {
              g_object_unref (*ex1);
            }
            *ex1 = g_object_new (TYPE_CURATOR_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ex1), protocol, error)) < 0)
            {
              g_object_unref (*ex1);
              *ex1 = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ex1 != NULL)
  {
      g_set_error (error, CURATOR_EXCEPTION_ERROR, CURATOR_EXCEPTION_ERROR_CODE, "CuratorException");
      return FALSE;
  }
  return TRUE;
}

gboolean discovery_service_client_make_discovery_instance (DiscoveryServiceIf * iface, DiscoveryInstance ** _return, const gchar * name, const GByteArray * payload, const gint32 port, CuratorException ** ex1, GError ** error)
{
  if (!discovery_service_client_send_make_discovery_instance (iface, name, payload, port, error))
    return FALSE;
  if (!discovery_service_client_recv_make_discovery_instance (iface, _return, ex1, error))
    return FALSE;
  return TRUE;
}

gboolean discovery_service_client_send_note_error (DiscoveryServiceIf * iface, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, const gchar * instanceId, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "noteError", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "noteError_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "projection", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (projection), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "providerProjection", T_STRUCT, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (providerProjection), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "instanceId", T_STRING, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, instanceId, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean discovery_service_client_recv_note_error (DiscoveryServiceIf * iface, CuratorException ** ex1, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "noteError", 9) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected noteError", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ex1 != NULL)
            {
              g_object_unref (*ex1);
            }
            *ex1 = g_object_new (TYPE_CURATOR_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ex1), protocol, error)) < 0)
            {
              g_object_unref (*ex1);
              *ex1 = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ex1 != NULL)
  {
      g_set_error (error, CURATOR_EXCEPTION_ERROR, CURATOR_EXCEPTION_ERROR_CODE, "CuratorException");
      return FALSE;
  }
  return TRUE;
}

gboolean discovery_service_client_note_error (DiscoveryServiceIf * iface, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, const gchar * instanceId, CuratorException ** ex1, GError ** error)
{
  if (!discovery_service_client_send_note_error (iface, projection, providerProjection, instanceId, error))
    return FALSE;
  if (!discovery_service_client_recv_note_error (iface, ex1, error))
    return FALSE;
  return TRUE;
}

gboolean discovery_service_client_send_start_discovery (DiscoveryServiceIf * iface, const CuratorProjection * projection, const gchar * basePath, const DiscoveryInstance * yourInstance, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "startDiscovery", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "startDiscovery_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "projection", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (projection), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "basePath", T_STRING, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, basePath, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "yourInstance", T_STRUCT, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (yourInstance), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean discovery_service_client_recv_start_discovery (DiscoveryServiceIf * iface, DiscoveryProjection ** _return, CuratorException ** ex1, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "startDiscovery", 14) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected startDiscovery", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ex1 != NULL)
            {
              g_object_unref (*ex1);
            }
            *ex1 = g_object_new (TYPE_CURATOR_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ex1), protocol, error)) < 0)
            {
              g_object_unref (*ex1);
              *ex1 = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ex1 != NULL)
  {
      g_set_error (error, CURATOR_EXCEPTION_ERROR, CURATOR_EXCEPTION_ERROR_CODE, "CuratorException");
      return FALSE;
  }
  return TRUE;
}

gboolean discovery_service_client_start_discovery (DiscoveryServiceIf * iface, DiscoveryProjection ** _return, const CuratorProjection * projection, const gchar * basePath, const DiscoveryInstance * yourInstance, CuratorException ** ex1, GError ** error)
{
  if (!discovery_service_client_send_start_discovery (iface, projection, basePath, yourInstance, error))
    return FALSE;
  if (!discovery_service_client_recv_start_discovery (iface, _return, ex1, error))
    return FALSE;
  return TRUE;
}

gboolean discovery_service_client_send_start_provider (DiscoveryServiceIf * iface, const CuratorProjection * projection, const DiscoveryProjection * discoveryProjection, const gchar * serviceName, const ProviderStrategyType providerStrategy, const gint32 downTimeoutMs, const gint32 downErrorThreshold, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "startProvider", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "startProvider_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "projection", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (projection), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "discoveryProjection", T_STRUCT, 2, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (discoveryProjection), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "serviceName", T_STRING, 3, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, serviceName, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "providerStrategy", T_I32, 4, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, (gint32) providerStrategy, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "downTimeoutMs", T_I32, 5, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, downTimeoutMs, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "downErrorThreshold", T_I32, 6, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_i32 (protocol, downErrorThreshold, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean discovery_service_client_recv_start_provider (DiscoveryServiceIf * iface, DiscoveryProviderProjection ** _return, CuratorException ** ex1, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = DISCOVERY_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "startProvider", 13) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected startProvider", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ex1 != NULL)
            {
              g_object_unref (*ex1);
            }
            *ex1 = g_object_new (TYPE_CURATOR_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ex1), protocol, error)) < 0)
            {
              g_object_unref (*ex1);
              *ex1 = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ex1 != NULL)
  {
      g_set_error (error, CURATOR_EXCEPTION_ERROR, CURATOR_EXCEPTION_ERROR_CODE, "CuratorException");
      return FALSE;
  }
  return TRUE;
}

gboolean discovery_service_client_start_provider (DiscoveryServiceIf * iface, DiscoveryProviderProjection ** _return, const CuratorProjection * projection, const DiscoveryProjection * discoveryProjection, const gchar * serviceName, const ProviderStrategyType providerStrategy, const gint32 downTimeoutMs, const gint32 downErrorThreshold, CuratorException ** ex1, GError ** error)
{
  if (!discovery_service_client_send_start_provider (iface, projection, discoveryProjection, serviceName, providerStrategy, downTimeoutMs, downErrorThreshold, error))
    return FALSE;
  if (!discovery_service_client_recv_start_provider (iface, _return, ex1, error))
    return FALSE;
  return TRUE;
}

static void
discovery_service_if_interface_init (DiscoveryServiceIfInterface *iface)
{
  iface->get_all_instances = discovery_service_client_get_all_instances;
  iface->get_instance = discovery_service_client_get_instance;
  iface->make_discovery_instance = discovery_service_client_make_discovery_instance;
  iface->note_error = discovery_service_client_note_error;
  iface->start_discovery = discovery_service_client_start_discovery;
  iface->start_provider = discovery_service_client_start_provider;
}

static void
discovery_service_client_init (DiscoveryServiceClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
discovery_service_client_class_init (DiscoveryServiceClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = discovery_service_client_set_property;
  gobject_class->get_property = discovery_service_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_DISCOVERY_SERVICE_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_DISCOVERY_SERVICE_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
discovery_service_handler_discovery_service_if_interface_init (DiscoveryServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (DiscoveryServiceHandler, 
                         discovery_service_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (TYPE_DISCOVERY_SERVICE_IF,
                                                discovery_service_handler_discovery_service_if_interface_init))

gboolean discovery_service_handler_get_all_instances (DiscoveryServiceIf * iface, GPtrArray ** _return, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, CuratorException ** ex1, GError ** error)
{
  g_return_val_if_fail (IS_DISCOVERY_SERVICE_HANDLER (iface), FALSE);

  return DISCOVERY_SERVICE_HANDLER_GET_CLASS (iface)->get_all_instances (iface, _return, projection, providerProjection, ex1, error);
}

gboolean discovery_service_handler_get_instance (DiscoveryServiceIf * iface, DiscoveryInstance ** _return, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, CuratorException ** ex1, GError ** error)
{
  g_return_val_if_fail (IS_DISCOVERY_SERVICE_HANDLER (iface), FALSE);

  return DISCOVERY_SERVICE_HANDLER_GET_CLASS (iface)->get_instance (iface, _return, projection, providerProjection, ex1, error);
}

gboolean discovery_service_handler_make_discovery_instance (DiscoveryServiceIf * iface, DiscoveryInstance ** _return, const gchar * name, const GByteArray * payload, const gint32 port, CuratorException ** ex1, GError ** error)
{
  g_return_val_if_fail (IS_DISCOVERY_SERVICE_HANDLER (iface), FALSE);

  return DISCOVERY_SERVICE_HANDLER_GET_CLASS (iface)->make_discovery_instance (iface, _return, name, payload, port, ex1, error);
}

gboolean discovery_service_handler_note_error (DiscoveryServiceIf * iface, const CuratorProjection * projection, const DiscoveryProviderProjection * providerProjection, const gchar * instanceId, CuratorException ** ex1, GError ** error)
{
  g_return_val_if_fail (IS_DISCOVERY_SERVICE_HANDLER (iface), FALSE);

  return DISCOVERY_SERVICE_HANDLER_GET_CLASS (iface)->note_error (iface, projection, providerProjection, instanceId, ex1, error);
}

gboolean discovery_service_handler_start_discovery (DiscoveryServiceIf * iface, DiscoveryProjection ** _return, const CuratorProjection * projection, const gchar * basePath, const DiscoveryInstance * yourInstance, CuratorException ** ex1, GError ** error)
{
  g_return_val_if_fail (IS_DISCOVERY_SERVICE_HANDLER (iface), FALSE);

  return DISCOVERY_SERVICE_HANDLER_GET_CLASS (iface)->start_discovery (iface, _return, projection, basePath, yourInstance, ex1, error);
}

gboolean discovery_service_handler_start_provider (DiscoveryServiceIf * iface, DiscoveryProviderProjection ** _return, const CuratorProjection * projection, const DiscoveryProjection * discoveryProjection, const gchar * serviceName, const ProviderStrategyType providerStrategy, const gint32 downTimeoutMs, const gint32 downErrorThreshold, CuratorException ** ex1, GError ** error)
{
  g_return_val_if_fail (IS_DISCOVERY_SERVICE_HANDLER (iface), FALSE);

  return DISCOVERY_SERVICE_HANDLER_GET_CLASS (iface)->start_provider (iface, _return, projection, discoveryProjection, serviceName, providerStrategy, downTimeoutMs, downErrorThreshold, ex1, error);
}

static void
discovery_service_handler_discovery_service_if_interface_init (DiscoveryServiceIfInterface *iface)
{
  iface->get_all_instances = discovery_service_handler_get_all_instances;
  iface->get_instance = discovery_service_handler_get_instance;
  iface->make_discovery_instance = discovery_service_handler_make_discovery_instance;
  iface->note_error = discovery_service_handler_note_error;
  iface->start_discovery = discovery_service_handler_start_discovery;
  iface->start_provider = discovery_service_handler_start_provider;
}

static void
discovery_service_handler_init (DiscoveryServiceHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
discovery_service_handler_class_init (DiscoveryServiceHandlerClass *cls)
{
  cls->get_all_instances = NULL;
  cls->get_instance = NULL;
  cls->make_discovery_instance = NULL;
  cls->note_error = NULL;
  cls->start_discovery = NULL;
  cls->start_provider = NULL;
}

enum _DiscoveryServiceProcessorProperties
{
  PROP_DISCOVERY_SERVICE_PROCESSOR_0,
  PROP_DISCOVERY_SERVICE_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (DiscoveryServiceProcessor,
               discovery_service_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* DiscoveryServiceProcessorProcessFunction) (DiscoveryServiceProcessor *, 
                                                               gint32,
                                                               ThriftProtocol *,
                                                               ThriftProtocol *,
                                                               GError **);

typedef struct
{
  gchar *name;
  DiscoveryServiceProcessorProcessFunction function;
} discovery_service_processor_process_function_def;

static gboolean
discovery_service_processor_process_get_all_instances (DiscoveryServiceProcessor *,
                                                       gint32,
                                                       ThriftProtocol *,
                                                       ThriftProtocol *,
                                                       GError **);
static gboolean
discovery_service_processor_process_get_instance (DiscoveryServiceProcessor *,
                                                  gint32,
                                                  ThriftProtocol *,
                                                  ThriftProtocol *,
                                                  GError **);
static gboolean
discovery_service_processor_process_make_discovery_instance (DiscoveryServiceProcessor *,
                                                             gint32,
                                                             ThriftProtocol *,
                                                             ThriftProtocol *,
                                                             GError **);
static gboolean
discovery_service_processor_process_note_error (DiscoveryServiceProcessor *,
                                                gint32,
                                                ThriftProtocol *,
                                                ThriftProtocol *,
                                                GError **);
static gboolean
discovery_service_processor_process_start_discovery (DiscoveryServiceProcessor *,
                                                     gint32,
                                                     ThriftProtocol *,
                                                     ThriftProtocol *,
                                                     GError **);
static gboolean
discovery_service_processor_process_start_provider (DiscoveryServiceProcessor *,
                                                    gint32,
                                                    ThriftProtocol *,
                                                    ThriftProtocol *,
                                                    GError **);

static discovery_service_processor_process_function_def
discovery_service_processor_process_function_defs[6] = {
  {
    "getAllInstances",
    discovery_service_processor_process_get_all_instances
  },
  {
    "getInstance",
    discovery_service_processor_process_get_instance
  },
  {
    "makeDiscoveryInstance",
    discovery_service_processor_process_make_discovery_instance
  },
  {
    "noteError",
    discovery_service_processor_process_note_error
  },
  {
    "startDiscovery",
    discovery_service_processor_process_start_discovery
  },
  {
    "startProvider",
    discovery_service_processor_process_start_provider
  }
};

static gboolean
discovery_service_processor_process_get_all_instances (DiscoveryServiceProcessor *self,
                                                       gint32 sequence_id,
                                                       ThriftProtocol *input_protocol,
                                                       ThriftProtocol *output_protocol,
                                                       GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  DiscoveryServiceGetAllInstancesArgs * args =
    g_object_new (TYPE_DISCOVERY_SERVICE_GET_ALL_INSTANCES_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    CuratorProjection * projection;
    DiscoveryProviderProjection * providerProjection;
    CuratorException * ex1 = NULL;
    GPtrArray * return_value;
    DiscoveryServiceGetAllInstancesResult * result_struct;

    g_object_get (args,
                  "projection", &projection,
                  "providerProjection", &providerProjection,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_DISCOVERY_SERVICE_GET_ALL_INSTANCES_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (discovery_service_handler_get_all_instances (DISCOVERY_SERVICE_IF (self->handler),
                                                     &return_value,
                                                     projection,
                                                     providerProjection,
                                                     &ex1,
                                                     error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_ptr_array_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "getAllInstances",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ex1 != NULL)
      {
        g_object_set (result_struct,
                      "ex1", ex1,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "getAllInstances",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("DiscoveryService.getAllInstances implementation returned FALSE "
                     "but did not set an error");

        xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "getAllInstances",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (projection != NULL)
      g_object_unref (projection);
    if (providerProjection != NULL)
      g_object_unref (providerProjection);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
discovery_service_processor_process_get_instance (DiscoveryServiceProcessor *self,
                                                  gint32 sequence_id,
                                                  ThriftProtocol *input_protocol,
                                                  ThriftProtocol *output_protocol,
                                                  GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  DiscoveryServiceGetInstanceArgs * args =
    g_object_new (TYPE_DISCOVERY_SERVICE_GET_INSTANCE_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    CuratorProjection * projection;
    DiscoveryProviderProjection * providerProjection;
    CuratorException * ex1 = NULL;
    DiscoveryInstance * return_value;
    DiscoveryServiceGetInstanceResult * result_struct;

    g_object_get (args,
                  "projection", &projection,
                  "providerProjection", &providerProjection,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_DISCOVERY_SERVICE_GET_INSTANCE_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (discovery_service_handler_get_instance (DISCOVERY_SERVICE_IF (self->handler),
                                                &return_value,
                                                projection,
                                                providerProjection,
                                                &ex1,
                                                error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "getInstance",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ex1 != NULL)
      {
        g_object_set (result_struct,
                      "ex1", ex1,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "getInstance",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("DiscoveryService.getInstance implementation returned FALSE "
                     "but did not set an error");

        xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "getInstance",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (projection != NULL)
      g_object_unref (projection);
    if (providerProjection != NULL)
      g_object_unref (providerProjection);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
discovery_service_processor_process_make_discovery_instance (DiscoveryServiceProcessor *self,
                                                             gint32 sequence_id,
                                                             ThriftProtocol *input_protocol,
                                                             ThriftProtocol *output_protocol,
                                                             GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  DiscoveryServiceMakeDiscoveryInstanceArgs * args =
    g_object_new (TYPE_DISCOVERY_SERVICE_MAKE_DISCOVERY_INSTANCE_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gchar * name;
    GByteArray * payload;
    gint port;
    CuratorException * ex1 = NULL;
    DiscoveryInstance * return_value;
    DiscoveryServiceMakeDiscoveryInstanceResult * result_struct;

    g_object_get (args,
                  "name", &name,
                  "payload", &payload,
                  "port", &port,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_DISCOVERY_SERVICE_MAKE_DISCOVERY_INSTANCE_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (discovery_service_handler_make_discovery_instance (DISCOVERY_SERVICE_IF (self->handler),
                                                           &return_value,
                                                           name,
                                                           payload,
                                                           port,
                                                           &ex1,
                                                           error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "makeDiscoveryInstance",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ex1 != NULL)
      {
        g_object_set (result_struct,
                      "ex1", ex1,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "makeDiscoveryInstance",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("DiscoveryService.makeDiscoveryInstance implementation returned FALSE "
                     "but did not set an error");

        xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "makeDiscoveryInstance",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (name != NULL)
      g_free (name);
    if (payload != NULL)
      g_byte_array_unref (payload);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
discovery_service_processor_process_note_error (DiscoveryServiceProcessor *self,
                                                gint32 sequence_id,
                                                ThriftProtocol *input_protocol,
                                                ThriftProtocol *output_protocol,
                                                GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  DiscoveryServiceNoteErrorArgs * args =
    g_object_new (TYPE_DISCOVERY_SERVICE_NOTE_ERROR_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    CuratorProjection * projection;
    DiscoveryProviderProjection * providerProjection;
    gchar * instanceId;
    CuratorException * ex1 = NULL;
    DiscoveryServiceNoteErrorResult * result_struct;

    g_object_get (args,
                  "projection", &projection,
                  "providerProjection", &providerProjection,
                  "instanceId", &instanceId,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_DISCOVERY_SERVICE_NOTE_ERROR_RESULT, NULL);

    if (discovery_service_handler_note_error (DISCOVERY_SERVICE_IF (self->handler),
                                              projection,
                                              providerProjection,
                                              instanceId,
                                              &ex1,
                                              error) == TRUE)
    {
      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "noteError",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ex1 != NULL)
      {
        g_object_set (result_struct,
                      "ex1", ex1,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "noteError",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("DiscoveryService.noteError implementation returned FALSE "
                     "but did not set an error");

        xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "noteError",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (projection != NULL)
      g_object_unref (projection);
    if (providerProjection != NULL)
      g_object_unref (providerProjection);
    if (instanceId != NULL)
      g_free (instanceId);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
discovery_service_processor_process_start_discovery (DiscoveryServiceProcessor *self,
                                                     gint32 sequence_id,
                                                     ThriftProtocol *input_protocol,
                                                     ThriftProtocol *output_protocol,
                                                     GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  DiscoveryServiceStartDiscoveryArgs * args =
    g_object_new (TYPE_DISCOVERY_SERVICE_START_DISCOVERY_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    CuratorProjection * projection;
    gchar * basePath;
    DiscoveryInstance * yourInstance;
    CuratorException * ex1 = NULL;
    DiscoveryProjection * return_value;
    DiscoveryServiceStartDiscoveryResult * result_struct;

    g_object_get (args,
                  "projection", &projection,
                  "basePath", &basePath,
                  "yourInstance", &yourInstance,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_DISCOVERY_SERVICE_START_DISCOVERY_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (discovery_service_handler_start_discovery (DISCOVERY_SERVICE_IF (self->handler),
                                                   &return_value,
                                                   projection,
                                                   basePath,
                                                   yourInstance,
                                                   &ex1,
                                                   error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "startDiscovery",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ex1 != NULL)
      {
        g_object_set (result_struct,
                      "ex1", ex1,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "startDiscovery",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("DiscoveryService.startDiscovery implementation returned FALSE "
                     "but did not set an error");

        xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "startDiscovery",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (projection != NULL)
      g_object_unref (projection);
    if (basePath != NULL)
      g_free (basePath);
    if (yourInstance != NULL)
      g_object_unref (yourInstance);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
discovery_service_processor_process_start_provider (DiscoveryServiceProcessor *self,
                                                    gint32 sequence_id,
                                                    ThriftProtocol *input_protocol,
                                                    ThriftProtocol *output_protocol,
                                                    GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  DiscoveryServiceStartProviderArgs * args =
    g_object_new (TYPE_DISCOVERY_SERVICE_START_PROVIDER_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    CuratorProjection * projection;
    DiscoveryProjection * discoveryProjection;
    gchar * serviceName;
    ProviderStrategyType providerStrategy;
    gint downTimeoutMs;
    gint downErrorThreshold;
    CuratorException * ex1 = NULL;
    DiscoveryProviderProjection * return_value;
    DiscoveryServiceStartProviderResult * result_struct;

    g_object_get (args,
                  "projection", &projection,
                  "discoveryProjection", &discoveryProjection,
                  "serviceName", &serviceName,
                  "providerStrategy", &providerStrategy,
                  "downTimeoutMs", &downTimeoutMs,
                  "downErrorThreshold", &downErrorThreshold,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_DISCOVERY_SERVICE_START_PROVIDER_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (discovery_service_handler_start_provider (DISCOVERY_SERVICE_IF (self->handler),
                                                  &return_value,
                                                  projection,
                                                  discoveryProjection,
                                                  serviceName,
                                                  providerStrategy,
                                                  downTimeoutMs,
                                                  downErrorThreshold,
                                                  &ex1,
                                                  error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "startProvider",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ex1 != NULL)
      {
        g_object_set (result_struct,
                      "ex1", ex1,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "startProvider",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("DiscoveryService.startProvider implementation returned FALSE "
                     "but did not set an error");

        xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "startProvider",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (projection != NULL)
      g_object_unref (projection);
    if (discoveryProjection != NULL)
      g_object_unref (discoveryProjection);
    if (serviceName != NULL)
      g_free (serviceName);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
discovery_service_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                           ThriftProtocol *input_protocol,
                                           ThriftProtocol *output_protocol,
                                           gchar *method_name,
                                           gint32 sequence_id,
                                           GError **error)
{
  discovery_service_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  DiscoveryServiceProcessor *self = DISCOVERY_SERVICE_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (DISCOVERY_SERVICE_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
discovery_service_processor_set_property (GObject *object,
                                          guint property_id,
                                          const GValue *value,
                                          GParamSpec *pspec)
{
  DiscoveryServiceProcessor *self = DISCOVERY_SERVICE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_DISCOVERY_SERVICE_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
discovery_service_processor_get_property (GObject *object,
                                          guint property_id,
                                          GValue *value,
                                          GParamSpec *pspec)
{
  DiscoveryServiceProcessor *self = DISCOVERY_SERVICE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_DISCOVERY_SERVICE_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
discovery_service_processor_dispose (GObject *gobject)
{
  DiscoveryServiceProcessor *self = DISCOVERY_SERVICE_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (discovery_service_processor_parent_class)->dispose (gobject);
}

static void
discovery_service_processor_finalize (GObject *gobject)
{
  DiscoveryServiceProcessor *self = DISCOVERY_SERVICE_PROCESSOR (gobject);

  g_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (discovery_service_processor_parent_class)->finalize (gobject);
}

static void
discovery_service_processor_init (DiscoveryServiceProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 6; index += 1)
    g_hash_table_insert (self->process_map,
                         discovery_service_processor_process_function_defs[index].name,
                         &discovery_service_processor_process_function_defs[index]);
}

static void
discovery_service_processor_class_init (DiscoveryServiceProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = discovery_service_processor_dispose;
  gobject_class->finalize = discovery_service_processor_finalize;
  gobject_class->set_property = discovery_service_processor_set_property;
  gobject_class->get_property = discovery_service_processor_get_property;

  dispatch_processor_class->dispatch_call = discovery_service_processor_dispatch_call;
  cls->dispatch_call = discovery_service_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    TYPE_DISCOVERY_SERVICE_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_DISCOVERY_SERVICE_PROCESSOR_HANDLER,
                                   param_spec);
}
