/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "event_service.h"

gboolean
event_service_if_get_next_event (EventServiceIf *iface, CuratorEvent ** _return, const CuratorProjection * projection, CuratorException ** ex1, GError **error)
{
  return EVENT_SERVICE_IF_GET_INTERFACE (iface)->get_next_event (iface, _return, projection, ex1, error);
}

GType
event_service_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (EventServiceIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "EventServiceIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
event_service_if_interface_init (EventServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (EventServiceClient, event_service_client,
                         G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (TYPE_EVENT_SERVICE_IF,
                                                event_service_if_interface_init))

enum _EventServiceClientProperties
{
  PROP_0,
  PROP_EVENT_SERVICE_CLIENT_INPUT_PROTOCOL,
  PROP_EVENT_SERVICE_CLIENT_OUTPUT_PROTOCOL
};

void
event_service_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  EventServiceClient *client = EVENT_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_EVENT_SERVICE_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_EVENT_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
event_service_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  EventServiceClient *client = EVENT_SERVICE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_EVENT_SERVICE_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_EVENT_SERVICE_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean event_service_client_send_get_next_event (EventServiceIf * iface, const CuratorProjection * projection, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = EVENT_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "getNextEvent", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "getNextEvent_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "projection", T_STRUCT, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_struct_write (THRIFT_STRUCT (projection), protocol, error)) < 0)
      return 0;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean event_service_client_recv_get_next_event (EventServiceIf * iface, CuratorEvent ** _return, CuratorException ** ex1, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = EVENT_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "getNextEvent", 12) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected getNextEvent", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRUCT)
          {
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*_return), protocol, error)) < 0)
            {
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        case 1:
          if (ftype == T_STRUCT)
          {
            /* This struct is an exception */
            if ( *ex1 != NULL)
            {
              g_object_unref (*ex1);
            }
            *ex1 = g_object_new (TYPE_CURATOR_EXCEPTION, NULL);
            if ((ret = thrift_struct_read (THRIFT_STRUCT (*ex1), protocol, error)) < 0)
            {
              g_object_unref (*ex1);
              *ex1 = NULL;
              return 0;
            }
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  if (*ex1 != NULL)
  {
      g_set_error (error, CURATOR_EXCEPTION_ERROR, CURATOR_EXCEPTION_ERROR_CODE, "CuratorException");
      return FALSE;
  }
  return TRUE;
}

gboolean event_service_client_get_next_event (EventServiceIf * iface, CuratorEvent ** _return, const CuratorProjection * projection, CuratorException ** ex1, GError ** error)
{
  if (!event_service_client_send_get_next_event (iface, projection, error))
    return FALSE;
  if (!event_service_client_recv_get_next_event (iface, _return, ex1, error))
    return FALSE;
  return TRUE;
}

static void
event_service_if_interface_init (EventServiceIfInterface *iface)
{
  iface->get_next_event = event_service_client_get_next_event;
}

static void
event_service_client_init (EventServiceClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
event_service_client_class_init (EventServiceClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = event_service_client_set_property;
  gobject_class->get_property = event_service_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_EVENT_SERVICE_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_EVENT_SERVICE_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

static void
event_service_handler_event_service_if_interface_init (EventServiceIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (EventServiceHandler, 
                         event_service_handler,
                         G_TYPE_OBJECT,
                         G_IMPLEMENT_INTERFACE (TYPE_EVENT_SERVICE_IF,
                                                event_service_handler_event_service_if_interface_init))

gboolean event_service_handler_get_next_event (EventServiceIf * iface, CuratorEvent ** _return, const CuratorProjection * projection, CuratorException ** ex1, GError ** error)
{
  g_return_val_if_fail (IS_EVENT_SERVICE_HANDLER (iface), FALSE);

  return EVENT_SERVICE_HANDLER_GET_CLASS (iface)->get_next_event (iface, _return, projection, ex1, error);
}

static void
event_service_handler_event_service_if_interface_init (EventServiceIfInterface *iface)
{
  iface->get_next_event = event_service_handler_get_next_event;
}

static void
event_service_handler_init (EventServiceHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
event_service_handler_class_init (EventServiceHandlerClass *cls)
{
  cls->get_next_event = NULL;
}

enum _EventServiceProcessorProperties
{
  PROP_EVENT_SERVICE_PROCESSOR_0,
  PROP_EVENT_SERVICE_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (EventServiceProcessor,
               event_service_processor,
               THRIFT_TYPE_DISPATCH_PROCESSOR)

typedef gboolean (* EventServiceProcessorProcessFunction) (EventServiceProcessor *, 
                                                           gint32,
                                                           ThriftProtocol *,
                                                           ThriftProtocol *,
                                                           GError **);

typedef struct
{
  gchar *name;
  EventServiceProcessorProcessFunction function;
} event_service_processor_process_function_def;

static gboolean
event_service_processor_process_get_next_event (EventServiceProcessor *,
                                                gint32,
                                                ThriftProtocol *,
                                                ThriftProtocol *,
                                                GError **);

static event_service_processor_process_function_def
event_service_processor_process_function_defs[1] = {
  {
    "getNextEvent",
    event_service_processor_process_get_next_event
  }
};

static gboolean
event_service_processor_process_get_next_event (EventServiceProcessor *self,
                                                gint32 sequence_id,
                                                ThriftProtocol *input_protocol,
                                                ThriftProtocol *output_protocol,
                                                GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  EventServiceGetNextEventArgs * args =
    g_object_new (TYPE_EVENT_SERVICE_GET_NEXT_EVENT_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    CuratorProjection * projection;
    CuratorException * ex1 = NULL;
    CuratorEvent * return_value;
    EventServiceGetNextEventResult * result_struct;

    g_object_get (args,
                  "projection", &projection,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_EVENT_SERVICE_GET_NEXT_EVENT_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (event_service_handler_get_next_event (EVENT_SERVICE_IF (self->handler),
                                              &return_value,
                                              projection,
                                              &ex1,
                                              error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_object_unref (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "getNextEvent",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (ex1 != NULL)
      {
        g_object_set (result_struct,
                      "ex1", ex1,
                      NULL);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "getNextEvent",
                                                 T_REPLY,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (result_struct),
                                 output_protocol,
                                 error) != -1));
      }
      else
      {
        if (*error == NULL)
          g_warning ("EventService.getNextEvent implementation returned FALSE "
                     "but did not set an error");

        xception =
          g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                        "type",    *error != NULL ? (*error)->code :
                                   THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                        "message", *error != NULL ? (*error)->message : NULL,
                        NULL);
        g_clear_error (error);

        result =
          ((thrift_protocol_write_message_begin (output_protocol,
                                                 "getNextEvent",
                                                 T_EXCEPTION,
                                                 sequence_id,
                                                 error) != -1) &&
           (thrift_struct_write (THRIFT_STRUCT (xception),
                                 output_protocol,
                                 error) != -1));

        g_object_unref (xception);
      }
    }

    if (projection != NULL)
      g_object_unref (projection);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
event_service_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                       ThriftProtocol *input_protocol,
                                       ThriftProtocol *output_protocol,
                                       gchar *method_name,
                                       gint32 sequence_id,
                                       GError **error)
{
  event_service_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  EventServiceProcessor *self = EVENT_SERVICE_PROCESSOR (dispatch_processor);
  ThriftDispatchProcessorClass *parent_class =
    g_type_class_peek_parent (EVENT_SERVICE_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
event_service_processor_set_property (GObject *object,
                                      guint property_id,
                                      const GValue *value,
                                      GParamSpec *pspec)
{
  EventServiceProcessor *self = EVENT_SERVICE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_EVENT_SERVICE_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
event_service_processor_get_property (GObject *object,
                                      guint property_id,
                                      GValue *value,
                                      GParamSpec *pspec)
{
  EventServiceProcessor *self = EVENT_SERVICE_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_EVENT_SERVICE_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
event_service_processor_dispose (GObject *gobject)
{
  EventServiceProcessor *self = EVENT_SERVICE_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (event_service_processor_parent_class)->dispose (gobject);
}

static void
event_service_processor_finalize (GObject *gobject)
{
  EventServiceProcessor *self = EVENT_SERVICE_PROCESSOR (gobject);

  g_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (event_service_processor_parent_class)->finalize (gobject);
}

static void
event_service_processor_init (EventServiceProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 1; index += 1)
    g_hash_table_insert (self->process_map,
                         event_service_processor_process_function_defs[index].name,
                         &event_service_processor_process_function_defs[index]);
}

static void
event_service_processor_class_init (EventServiceProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = event_service_processor_dispose;
  gobject_class->finalize = event_service_processor_finalize;
  gobject_class->set_property = event_service_processor_set_property;
  gobject_class->get_property = event_service_processor_get_property;

  dispatch_processor_class->dispatch_call = event_service_processor_dispatch_call;
  cls->dispatch_call = event_service_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    TYPE_EVENT_SERVICE_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_EVENT_SERVICE_PROCESSOR_HANDLER,
                                   param_spec);
}
