/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "curator_constants.h"

namespace shared {

const curatorConstants g_curator_constants;

curatorConstants::curatorConstants() {
}

} // namespace

