/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include <string.h>
#include <thrift/c_glib/thrift.h>
#include <thrift/c_glib/thrift_application_exception.h>
#include "cci_mini_clang_rpc.h"

gboolean
cci_mini_clang_rpc_if_perform_diag (cci_mini_clang_rpcIf *iface, gchar ** _return, const gchar * index_module, GError **error)
{
  return CCI_MINI_CLANG_RPC_IF_GET_INTERFACE (iface)->perform_diag (iface, _return, index_module, error);
}

GType
cci_mini_clang_rpc_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (cci_mini_clang_rpcIfInterface),
      NULL,  /* base_init */
      NULL,  /* base_finalize */
      NULL,  /* class_init */
      NULL,  /* class_finalize */
      NULL,  /* class_data */
      0,     /* instance_size */
      0,     /* n_preallocs */
      NULL,  /* instance_init */
      NULL   /* value_table */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "cci_mini_clang_rpcIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
cci_mini_clang_rpc_if_interface_init (cci_mini_clang_rpcIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (cci_mini_clang_rpcClient, cci_mini_clang_rpc_client,
                         TYPE_SHARED_SERVICE_CLIENT, 
                         G_IMPLEMENT_INTERFACE (TYPE_CCI_MINI_CLANG_RPC_IF,
                                                cci_mini_clang_rpc_if_interface_init))

gboolean cci_mini_clang_rpc_client_send_perform_diag (cci_mini_clang_rpcIf * iface, const gchar * index_module, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = SHARED_SERVICE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "perform_diag", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "perform_diag_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "index_module", T_STRING, 1, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_string (protocol, index_module, error)) < 0)
      return 0;
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean cci_mini_clang_rpc_client_recv_perform_diag (cci_mini_clang_rpcIf * iface, gchar ** _return, GError ** error)
{
  gint32 rseqid;
  gchar * fname = NULL;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = SHARED_SERVICE_CLIENT (iface)->input_protocol;
  ThriftApplicationException *xception;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0) {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR,xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "perform_diag", 12) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol,error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected perform_diag", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name = NULL;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);
      name = NULL;

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_STRING)
          {
            if (*_return != NULL)
            {
              g_free(*_return);
              *_return = NULL;
            }

            if ((ret = thrift_protocol_read_string (protocol, &*_return, error)) < 0)
              return 0;
            xfer += ret;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean cci_mini_clang_rpc_client_perform_diag (cci_mini_clang_rpcIf * iface, gchar ** _return, const gchar * index_module, GError ** error)
{
  if (!cci_mini_clang_rpc_client_send_perform_diag (iface, index_module, error))
    return FALSE;
  if (!cci_mini_clang_rpc_client_recv_perform_diag (iface, _return, error))
    return FALSE;
  return TRUE;
}

static void
cci_mini_clang_rpc_if_interface_init (cci_mini_clang_rpcIfInterface *iface)
{
  iface->perform_diag = cci_mini_clang_rpc_client_perform_diag;
}

static void
cci_mini_clang_rpc_client_init (cci_mini_clang_rpcClient *client)
{
  THRIFT_UNUSED_VAR (client);
}

static void
cci_mini_clang_rpc_client_class_init (cci_mini_clang_rpcClientClass *cls)
{
  THRIFT_UNUSED_VAR (cls);
}

static void
cci_mini_clang_rpc_handler_cci_mini_clang_rpc_if_interface_init (cci_mini_clang_rpcIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (cci_mini_clang_rpcHandler, 
                         cci_mini_clang_rpc_handler,
                         TYPE_SHARED_SERVICE_HANDLER,
                         G_IMPLEMENT_INTERFACE (TYPE_CCI_MINI_CLANG_RPC_IF,
                                                cci_mini_clang_rpc_handler_cci_mini_clang_rpc_if_interface_init))

gboolean cci_mini_clang_rpc_handler_perform_diag (cci_mini_clang_rpcIf * iface, gchar ** _return, const gchar * index_module, GError ** error)
{
  g_return_val_if_fail (IS_CCI_MINI_CLANG_RPC_HANDLER (iface), FALSE);

  return CCI_MINI_CLANG_RPC_HANDLER_GET_CLASS (iface)->perform_diag (iface, _return, index_module, error);
}

static void
cci_mini_clang_rpc_handler_cci_mini_clang_rpc_if_interface_init (cci_mini_clang_rpcIfInterface *iface)
{
  iface->perform_diag = cci_mini_clang_rpc_handler_perform_diag;
}

static void
cci_mini_clang_rpc_handler_init (cci_mini_clang_rpcHandler *self)
{
  THRIFT_UNUSED_VAR (self);
}

static void
cci_mini_clang_rpc_handler_class_init (cci_mini_clang_rpcHandlerClass *cls)
{
  cls->perform_diag = NULL;
}

enum _cci_mini_clang_rpcProcessorProperties
{
  PROP_CCI_MINI_CLANG_RPC_PROCESSOR_0,
  PROP_CCI_MINI_CLANG_RPC_PROCESSOR_HANDLER
};

G_DEFINE_TYPE (cci_mini_clang_rpcProcessor,
               cci_mini_clang_rpc_processor,
               TYPE_SHARED_SERVICE_PROCESSOR)

typedef gboolean (* cci_mini_clang_rpcProcessorProcessFunction) (cci_mini_clang_rpcProcessor *, 
                                                                 gint32,
                                                                 ThriftProtocol *,
                                                                 ThriftProtocol *,
                                                                 GError **);

typedef struct
{
  gchar *name;
  cci_mini_clang_rpcProcessorProcessFunction function;
} cci_mini_clang_rpc_processor_process_function_def;

static gboolean
cci_mini_clang_rpc_processor_process_perform_diag (cci_mini_clang_rpcProcessor *,
                                                   gint32,
                                                   ThriftProtocol *,
                                                   ThriftProtocol *,
                                                   GError **);

static cci_mini_clang_rpc_processor_process_function_def
cci_mini_clang_rpc_processor_process_function_defs[1] = {
  {
    "perform_diag",
    cci_mini_clang_rpc_processor_process_perform_diag
  }
};

static gboolean
cci_mini_clang_rpc_processor_process_perform_diag (cci_mini_clang_rpcProcessor *self,
                                                   gint32 sequence_id,
                                                   ThriftProtocol *input_protocol,
                                                   ThriftProtocol *output_protocol,
                                                   GError **error)
{
  gboolean result = TRUE;
  ThriftTransport * transport;
  ThriftApplicationException *xception;
  cci_mini_clang_rpcPerformDiagArgs * args =
    g_object_new (TYPE_CCI_MINI_CLANG_RPC_PERFORM_DIAG_ARGS, NULL);

  g_object_get (input_protocol, "transport", &transport, NULL);

  if ((thrift_struct_read (THRIFT_STRUCT (args), input_protocol, error) != -1) &&
      (thrift_protocol_read_message_end (input_protocol, error) != -1) &&
      (thrift_transport_read_end (transport, error) != FALSE))
  {
    gchar * index_module;
    gchar * return_value;
    cci_mini_clang_rpcPerformDiagResult * result_struct;

    g_object_get (args,
                  "index_module", &index_module,
                  NULL);

    g_object_unref (transport);
    g_object_get (output_protocol, "transport", &transport, NULL);

    result_struct = g_object_new (TYPE_CCI_MINI_CLANG_RPC_PERFORM_DIAG_RESULT, NULL);
    g_object_get (result_struct, "success", &return_value, NULL);

    if (cci_mini_clang_rpc_handler_perform_diag (CCI_MINI_CLANG_RPC_IF (self->handler),
                                                 &return_value,
                                                 index_module,
                                                 error) == TRUE)
    {
      g_object_set (result_struct, "success", return_value, NULL);
      if (return_value != NULL)
        g_free (return_value);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "perform_diag",
                                               T_REPLY,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (result_struct),
                               output_protocol,
                               error) != -1));
    }
    else
    {
      if (*error == NULL)
        g_warning ("cci_mini_clang_rpc.perform_diag implementation returned FALSE "
                   "but did not set an error");

      xception =
        g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION,
                      "type",    *error != NULL ? (*error)->code :
                                 THRIFT_APPLICATION_EXCEPTION_ERROR_UNKNOWN,
                      "message", *error != NULL ? (*error)->message : NULL,
                      NULL);
      g_clear_error (error);

      result =
        ((thrift_protocol_write_message_begin (output_protocol,
                                               "perform_diag",
                                               T_EXCEPTION,
                                               sequence_id,
                                               error) != -1) &&
         (thrift_struct_write (THRIFT_STRUCT (xception),
                               output_protocol,
                               error) != -1));

      g_object_unref (xception);
    }

    if (index_module != NULL)
      g_free (index_module);
    g_object_unref (result_struct);

    if (result == TRUE)
      result =
        ((thrift_protocol_write_message_end (output_protocol, error) != -1) &&
         (thrift_transport_write_end (transport, error) != FALSE) &&
         (thrift_transport_flush (transport, error) != FALSE));
  }
  else
    result = FALSE;

  g_object_unref (transport);
  g_object_unref (args);

  return result;
}

static gboolean
cci_mini_clang_rpc_processor_dispatch_call (ThriftDispatchProcessor *dispatch_processor,
                                            ThriftProtocol *input_protocol,
                                            ThriftProtocol *output_protocol,
                                            gchar *method_name,
                                            gint32 sequence_id,
                                            GError **error)
{
  cci_mini_clang_rpc_processor_process_function_def *process_function_def;
  gboolean dispatch_result = FALSE;

  cci_mini_clang_rpcProcessor *self = CCI_MINI_CLANG_RPC_PROCESSOR (dispatch_processor);
  SharedServiceProcessorClass *parent_class =
    g_type_class_peek_parent (CCI_MINI_CLANG_RPC_PROCESSOR_GET_CLASS (self));

  process_function_def = g_hash_table_lookup (self->process_map, method_name);
  if (process_function_def != NULL)
  {
    dispatch_result = (*process_function_def->function) (self,
                                                         sequence_id,
                                                         input_protocol,
                                                         output_protocol,
                                                         error);
  }
  else
  {
    dispatch_result = parent_class->dispatch_call (dispatch_processor,
                                                   input_protocol,
                                                   output_protocol,
                                                   method_name,
                                                   sequence_id,
                                                   error);
  }

  return dispatch_result;
}

static void
cci_mini_clang_rpc_processor_set_property (GObject *object,
                                           guint property_id,
                                           const GValue *value,
                                           GParamSpec *pspec)
{
  cci_mini_clang_rpcProcessor *self = CCI_MINI_CLANG_RPC_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_CCI_MINI_CLANG_RPC_PROCESSOR_HANDLER:
      if (self->handler != NULL)
        g_object_unref (self->handler);
      self->handler = g_value_get_object (value);
      g_object_ref (self->handler);

      G_OBJECT_CLASS (cci_mini_clang_rpc_processor_parent_class)->
        set_property (object, property_id, value, pspec);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
cci_mini_clang_rpc_processor_get_property (GObject *object,
                                           guint property_id,
                                           GValue *value,
                                           GParamSpec *pspec)
{
  cci_mini_clang_rpcProcessor *self = CCI_MINI_CLANG_RPC_PROCESSOR (object);

  switch (property_id)
  {
    case PROP_CCI_MINI_CLANG_RPC_PROCESSOR_HANDLER:
      g_value_set_object (value, self->handler);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
cci_mini_clang_rpc_processor_dispose (GObject *gobject)
{
  cci_mini_clang_rpcProcessor *self = CCI_MINI_CLANG_RPC_PROCESSOR (gobject);

  if (self->handler != NULL)
  {
    g_object_unref (self->handler);
    self->handler = NULL;
  }

  G_OBJECT_CLASS (cci_mini_clang_rpc_processor_parent_class)->dispose (gobject);
}

static void
cci_mini_clang_rpc_processor_finalize (GObject *gobject)
{
  cci_mini_clang_rpcProcessor *self = CCI_MINI_CLANG_RPC_PROCESSOR (gobject);

  g_hash_table_destroy (self->process_map);

  G_OBJECT_CLASS (cci_mini_clang_rpc_processor_parent_class)->finalize (gobject);
}

static void
cci_mini_clang_rpc_processor_init (cci_mini_clang_rpcProcessor *self)
{
  guint index;

  self->handler = NULL;
  self->process_map = g_hash_table_new (g_str_hash, g_str_equal);

  for (index = 0; index < 1; index += 1)
    g_hash_table_insert (self->process_map,
                         cci_mini_clang_rpc_processor_process_function_defs[index].name,
                         &cci_mini_clang_rpc_processor_process_function_defs[index]);
}

static void
cci_mini_clang_rpc_processor_class_init (cci_mini_clang_rpcProcessorClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftDispatchProcessorClass *dispatch_processor_class =
    THRIFT_DISPATCH_PROCESSOR_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->dispose = cci_mini_clang_rpc_processor_dispose;
  gobject_class->finalize = cci_mini_clang_rpc_processor_finalize;
  gobject_class->set_property = cci_mini_clang_rpc_processor_set_property;
  gobject_class->get_property = cci_mini_clang_rpc_processor_get_property;

  dispatch_processor_class->dispatch_call = cci_mini_clang_rpc_processor_dispatch_call;
  cls->dispatch_call = cci_mini_clang_rpc_processor_dispatch_call;

  param_spec = g_param_spec_object ("handler",
                                    "Service handler implementation",
                                    "The service handler implementation "
                                    "to which method calls are dispatched.",
                                    TYPE_CCI_MINI_CLANG_RPC_HANDLER,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_CCI_MINI_CLANG_RPC_PROCESSOR_HANDLER,
                                   param_spec);
}
